<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>data_map</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="data_map_files/libs/clipboard/clipboard.min.js"></script>
<script src="data_map_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="data_map_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="data_map_files/libs/quarto-html/popper.min.js"></script>
<script src="data_map_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data_map_files/libs/quarto-html/anchor.min.js"></script>
<link href="data_map_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data_map_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data_map_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data_map_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data_map_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="home-credit-data-map" class="level1">
<h1>Home Credit data map</h1>
<section id="scope-and-conventions" class="level2">
<h2 class="anchored" data-anchor-id="scope-and-conventions">Scope and conventions</h2>
<p>This is a structural data audit, not exploratory data analysis. It covers the nine data/output CSVs in <code>data/raw/</code>; <code>docs/HomeCredit_columns_description.csv</code> is treated as metadata rather than as a business table. The same dictionary also appears in <code>data/raw/</code>, and the two copies are byte-for-byte identical.</p>
<ul>
<li>Row counts exclude the header.</li>
<li>Keys are inferred from the dictionary and observed grain because the CSVs do not declare database constraints.</li>
<li>Cardinality is written from child to parent. <code>M:1</code> means many child rows may join to one parent row; the reverse relationship is <code>1:0..M</code> unless stated otherwise.</li>
<li>“Train coverage” is the number of distinct <code>application_train.SK_ID_CURR</code> values represented by at least one row, divided by 307,511 train applicants. For <code>bureau_balance</code>, coverage is measured indirectly through <code>bureau</code>.</li>
<li>A “value contradiction” is limited to an observed value that conflicts with an explicit domain or time meaning in the dictionary. Undocumented categories and schema discrepancies are also called out, but are not silently treated as domain violations.</li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Table</th>
<th>Grain</th>
<th style="text-align: right;">Rows</th>
<th>Inferred primary key</th>
<th>Unique?</th>
<th style="text-align: right;">Train applicants represented</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>application_train</code></td>
<td>One current Home Credit application/applicant</td>
<td style="text-align: right;">307,511</td>
<td><code>SK_ID_CURR</code></td>
<td>Yes</td>
<td style="text-align: right;">307,511 (100.00%)</td>
</tr>
<tr class="even">
<td><code>application_test</code></td>
<td>One held-out current Home Credit application/applicant</td>
<td style="text-align: right;">48,744</td>
<td><code>SK_ID_CURR</code></td>
<td>Yes</td>
<td style="text-align: right;">0 (0.00%)</td>
</tr>
<tr class="odd">
<td><code>bureau</code></td>
<td>One credit reported by the Credit Bureau for a current applicant</td>
<td style="text-align: right;">1,716,428</td>
<td><code>SK_ID_BUREAU</code></td>
<td>Yes</td>
<td style="text-align: right;">263,491 (85.69%)</td>
</tr>
<tr class="even">
<td><code>bureau_balance</code></td>
<td>One monthly status snapshot of one bureau credit</td>
<td style="text-align: right;">27,299,925</td>
<td>(<code>SK_ID_BUREAU</code>, <code>MONTHS_BALANCE</code>)</td>
<td>Yes</td>
<td style="text-align: right;">92,231 (29.99%), indirectly</td>
</tr>
<tr class="odd">
<td><code>previous_application</code></td>
<td>One previous Home Credit application</td>
<td style="text-align: right;">1,670,214</td>
<td><code>SK_ID_PREV</code></td>
<td>Yes</td>
<td style="text-align: right;">291,057 (94.65%)</td>
</tr>
<tr class="even">
<td><code>POS_CASH_balance</code></td>
<td>One monthly POS/cash-loan snapshot for a previous credit</td>
<td style="text-align: right;">10,001,358</td>
<td>(<code>SK_ID_PREV</code>, <code>MONTHS_BALANCE</code>)</td>
<td>Yes</td>
<td style="text-align: right;">289,444 (94.12%)</td>
</tr>
<tr class="odd">
<td><code>credit_card_balance</code></td>
<td>One monthly credit-card snapshot for a previous credit</td>
<td style="text-align: right;">3,840,312</td>
<td>(<code>SK_ID_PREV</code>, <code>MONTHS_BALANCE</code>)</td>
<td>Yes</td>
<td style="text-align: right;">86,905 (28.26%)</td>
</tr>
<tr class="even">
<td><code>installments_payments</code></td>
<td>One observed payment record against a scheduled installment</td>
<td style="text-align: right;">13,605,401</td>
<td>No unique row key supplied; see below</td>
<td>No</td>
<td style="text-align: right;">291,643 (94.84%)</td>
</tr>
<tr class="odd">
<td><code>sample_submission</code></td>
<td>One prediction placeholder for one test application</td>
<td style="text-align: right;">48,744</td>
<td><code>SK_ID_CURR</code></td>
<td>Yes</td>
<td style="text-align: right;">0 (0.00%)</td>
</tr>
</tbody>
</table>
</section>
<section id="table-details" class="level2">
<h2 class="anchored" data-anchor-id="table-details">Table details</h2>
<section id="application_train.csv" class="level3">
<h3 class="anchored" data-anchor-id="application_train.csv"><code>application_train.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one current Home Credit application/applicant; 307,511 rows.</li>
<li><strong>Primary key:</strong> <code>SK_ID_CURR</code>; all 307,511 values are unique.</li>
<li><strong>Foreign keys:</strong> none.</li>
<li><strong>Train coverage:</strong> 307,511 / 307,511 = <strong>100.00%</strong>.</li>
<li><strong>Value contradictions:</strong> <code>DAYS_EMPLOYED</code> is defined as how many days <em>before</em> the application employment began, but 55,374 rows contain the positive value <code>365243</code>. This is an undocumented sentinel, not a plausible relative-day value. <code>CODE_GENDER</code> also contains the undocumented category <code>XNA</code> in 4 rows; because the dictionary gives no allowed category list, this is an undocumented value rather than a strict domain violation.</li>
</ul>
</section>
<section id="application_test.csv" class="level3">
<h3 class="anchored" data-anchor-id="application_test.csv"><code>application_test.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one held-out current Home Credit application/applicant; 48,744 rows.</li>
<li><strong>Primary key:</strong> <code>SK_ID_CURR</code>; all 48,744 values are unique. The IDs are disjoint from train.</li>
<li><strong>Foreign keys:</strong> none.</li>
<li><strong>Train coverage:</strong> 0 / 307,511 = <strong>0.00%</strong>.</li>
<li><strong>Value contradictions:</strong> <code>DAYS_EMPLOYED</code> contains the same positive <code>365243</code> sentinel in 9,274 rows. <code>REGION_RATING_CLIENT_W_CITY</code>, whose documented domain is 1, 2, or 3, equals <code>-1</code> in 1 row.</li>
</ul>
</section>
<section id="bureau.csv" class="level3">
<h3 class="anchored" data-anchor-id="bureau.csv"><code>bureau.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one Credit Bureau credit associated with a current applicant; 1,716,428 rows.</li>
<li><strong>Primary key:</strong> <code>SK_ID_BUREAU</code>; all 1,716,428 values are unique.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_CURR</code> -&gt; the union of <code>application_train.SK_ID_CURR</code> and <code>application_test.SK_ID_CURR</code>, <strong>M:1</strong>. All rows resolve; each application has zero or many bureau credits.</li>
<li><strong>Train coverage:</strong> 263,491 / 307,511 = <strong>85.69%</strong>.</li>
<li><strong>Value contradictions:</strong> <code>DAYS_CREDIT_UPDATE</code> is documented as the number of days <em>before</em> the current application when the bureau information arrived, but 17 rows are positive (maximum <code>372</code>).</li>
</ul>
</section>
<section id="bureau_balance.csv" class="level3">
<h3 class="anchored" data-anchor-id="bureau_balance.csv"><code>bureau_balance.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one monthly balance/status snapshot for one bureau credit; 27,299,925 rows.</li>
<li><strong>Primary key:</strong> (<code>SK_ID_BUREAU</code>, <code>MONTHS_BALANCE</code>); all 27,299,925 combinations are unique.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_BUREAU</code> -&gt; <code>bureau.SK_ID_BUREAU</code>, expected <strong>M:1</strong>. The relationship is only partial in the supplied extracts: 24,179,741 rows resolve and 3,120,184 rows do not. A bureau credit has zero or many monthly snapshots among the matching records.</li>
<li><strong>Train coverage:</strong> 92,231 / 307,511 = <strong>29.99%</strong>, found by joining through the available <code>bureau</code> rows. Because some bureau IDs have no supplied parent, this is the measurable coverage, not necessarily the coverage of the source system.</li>
<li><strong>Value contradictions:</strong> <code>MONTHS_BALANCE</code> equals <code>0</code> in 610,965 rows even though this table’s dictionary entry says <code>-1</code> is the freshest balance date. Observed values range from <code>-96</code> through <code>0</code>.</li>
</ul>
</section>
<section id="previous_application.csv" class="level3">
<h3 class="anchored" data-anchor-id="previous_application.csv"><code>previous_application.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one previous Home Credit application, whether or not it became a credit; 1,670,214 rows.</li>
<li><strong>Primary key:</strong> <code>SK_ID_PREV</code>; all 1,670,214 values are unique.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_CURR</code> -&gt; the union of <code>application_train.SK_ID_CURR</code> and <code>application_test.SK_ID_CURR</code>, <strong>M:1</strong>. All rows resolve; each current application has zero or many previous applications.</li>
<li><strong>Train coverage:</strong> 291,057 / 307,511 = <strong>94.65%</strong>.</li>
<li><strong>Value contradictions:</strong> the undocumented sentinel <code>365243</code> appears in fields documented as relative dates: <code>DAYS_FIRST_DRAWING</code> (934,444 rows), <code>DAYS_FIRST_DUE</code> (40,645), <code>DAYS_LAST_DUE_1ST_VERSION</code> (93,864), <code>DAYS_LAST_DUE</code> (211,221), and <code>DAYS_TERMINATION</code> (225,913). The value is about 1,000 years and therefore is not a literal relative-day measurement.</li>
</ul>
</section>
<section id="pos_cash_balance.csv" class="level3">
<h3 class="anchored" data-anchor-id="pos_cash_balance.csv"><code>POS_CASH_balance.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one monthly POS/cash-loan balance snapshot for one previous credit; 10,001,358 rows.</li>
<li><strong>Primary key:</strong> (<code>SK_ID_PREV</code>, <code>MONTHS_BALANCE</code>); all 10,001,358 combinations are unique.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_CURR</code> -&gt; the union of train and test applications, <strong>M:1</strong>, with all rows resolved. <code>SK_ID_PREV</code> -&gt; <code>previous_application.SK_ID_PREV</code>, expected <strong>M:1</strong>, is partial: 9,660,797 rows resolve and 340,561 do not. For every row whose <code>SK_ID_PREV</code> resolves, its <code>SK_ID_CURR</code> agrees with the parent application.</li>
<li><strong>Train coverage:</strong> 289,444 / 307,511 = <strong>94.12%</strong>.</li>
<li><strong>Value contradictions:</strong> none found against explicit dictionary domains or meanings.</li>
</ul>
</section>
<section id="credit_card_balance.csv" class="level3">
<h3 class="anchored" data-anchor-id="credit_card_balance.csv"><code>credit_card_balance.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one monthly credit-card balance snapshot for one previous credit; 3,840,312 rows.</li>
<li><strong>Primary key:</strong> (<code>SK_ID_PREV</code>, <code>MONTHS_BALANCE</code>); all 3,840,312 combinations are unique.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_CURR</code> -&gt; the union of train and test applications, <strong>M:1</strong>, with all rows resolved. <code>SK_ID_PREV</code> -&gt; <code>previous_application.SK_ID_PREV</code>, expected <strong>M:1</strong>, is partial: 2,757,496 rows resolve and 1,082,816 do not. All resolved previous-credit rows agree on <code>SK_ID_CURR</code>.</li>
<li><strong>Train coverage:</strong> 86,905 / 307,511 = <strong>28.26%</strong>.</li>
<li><strong>Value contradictions:</strong> none found against explicit dictionary domains or meanings.</li>
</ul>
</section>
<section id="installments_payments.csv" class="level3">
<h3 class="anchored" data-anchor-id="installments_payments.csv"><code>installments_payments.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one observed payment record against a scheduled installment of a previous credit; 13,605,401 rows. Multiple records can apply to the same scheduled installment, consistent with split or repeated payments.</li>
<li><strong>Primary key:</strong> no unique row-level key is supplied. The natural schedule key (<code>SK_ID_PREV</code>, <code>NUM_INSTALMENT_VERSION</code>, <code>NUM_INSTALMENT_NUMBER</code>) has 12,951,918 distinct combinations and 653,483 excess duplicate occurrences, so it is <strong>not unique</strong> and cannot serve as this table’s primary key.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_CURR</code> -&gt; the union of train and test applications, <strong>M:1</strong>, with all rows resolved. <code>SK_ID_PREV</code> -&gt; <code>previous_application.SK_ID_PREV</code>, expected <strong>M:1</strong>, is partial: 12,354,575 rows resolve and 1,250,826 do not. All resolved previous-credit rows agree on <code>SK_ID_CURR</code>.</li>
<li><strong>Train coverage:</strong> 291,643 / 307,511 = <strong>94.84%</strong>.</li>
<li><strong>Value contradictions:</strong> none found against explicit dictionary domains or meanings.</li>
</ul>
</section>
<section id="sample_submission.csv" class="level3">
<h3 class="anchored" data-anchor-id="sample_submission.csv"><code>sample_submission.csv</code></h3>
<ul>
<li><strong>Grain and rows:</strong> one prediction placeholder per test application; 48,744 rows.</li>
<li><strong>Primary key:</strong> <code>SK_ID_CURR</code>; all values are unique.</li>
<li><strong>Foreign keys:</strong> <code>SK_ID_CURR</code> -&gt; <code>application_test.SK_ID_CURR</code>, <strong>1:1</strong>. Its ID set exactly equals the test ID set.</li>
<li><strong>Train coverage:</strong> 0 / 307,511 = <strong>0.00%</strong>.</li>
<li><strong>Value contradictions:</strong> not assessable from the supplied dictionary because <code>sample_submission.csv</code> is not documented there.</li>
</ul>
</section>
</section>
<section id="dictionaryschema-discrepancies" class="level2">
<h2 class="anchored" data-anchor-id="dictionaryschema-discrepancies">Dictionary/schema discrepancies</h2>
<ul>
<li>The dictionary uses <code>SK_BUREAU_ID</code> in <code>bureau</code> and <code>bureau_balance</code>; both actual CSVs use <code>SK_ID_BUREAU</code>.</li>
<li>The dictionary lists <code>NFLAG_MICRO_CASH</code> for <code>previous_application</code>, but that column is absent from the CSV.</li>
<li>The shared <code>application_{train|test}</code> dictionary lists <code>TARGET</code>; its absence from <code>application_test</code> is expected for a held-out scoring table, not treated as an error.</li>
<li><code>sample_submission.csv</code> has no entry in the dictionary.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>